name: wgpu_native
description: WGPU-Native Dart bindings.
version: 1.0.0

environment:
  sdk: '>=2.15.0-82.0.dev <3.0.0'

dependencies: 
  dylib: ^0.3.2+1
  ffi: ^1.1.2 

dev_dependencies:
  ffigen: ^4.1.1
  lints: ^1.0.1
  test: ^1.19.3

ffigen:
  name: LibWGPU
  output: 'lib/src/generated_bindings.dart'
  headers:
    entry-points:
      - 'ffi/webgpu.h'
      - 'ffi/wgpu.h'
